### ISSUE TITLE
Not found 

### ISSUE THREAD

**Issue by nasim-fani** [sthierolf/network-automation-scripts#4]
Hello,
I'm testing your code on a Debian 10 server.
This is what I got:

![image](https://user-images.githubusercontent.com/39902468/133886701-4d55df35-2228-4004-aeea-b5d4e406da02.png)

**Comment by sthierolf** [comment]
Hi,
checked on Debian 10 (Virtual Machine + WSL). Script says tests are passed.
In our Environment, do you have access to DNS without any restrictions (firewall, no internet, ...)?

The Tests can be performed also by nslookup or dig, for example:
    nslookup -type=txt microsoft.com
which should return the same result.
